
server:
  port: 9090
spring:
  application:
    name: employeeApi
  datasource:
    url: jdbc:mysql://localhost:3306/employeedb?createDatabaseIfNotExist=true
    username: root
    password: Mahesh@1998
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
